#include <stdlib.h>
#include <time.h>
#include <math.h>
#include <time.h>
#include <string.h>
#include <stdio.h>
#include <pthread.h>
#include "mmm.h"



/**
 * Allocate and initialize the matrices on the heap. Populate
 * the input matrices with random integers from 0 to 99
 */
void mmm_init()
{
	srand(time(NULL));

	//Wish I could genaralize this block!

	//For Matrix 1
	int a; //Loop var for all loops
	int b; //Also loop var for all loops
	matrixOne = (double **) malloc(sizeof (double*) *matrixSize); 
	for(a = 0; a < matrixSize; a++){
		matrixOne[a] = (double *) malloc(sizeof (double) *matrixSize);
	}
	
	for(a = 0; a < matrixSize; a++){
		for(b = 0; b < matrixSize; b++){
			matrixOne[a][b] = rand() % 100;
		}
	}
	
	//For Matrix 2
	matrixTwo = (double **) malloc(sizeof (double*) *matrixSize); 
	for(a = 0; a < matrixSize; a++){
		matrixTwo[a] = (double *) malloc(sizeof (double) *matrixSize);
	}
	
	for(a = 0; a < matrixSize; a++){
		for(b = 0; b < matrixSize; b++){
			matrixTwo[a][b] = rand() % 100;
		}
	}

	//Allocate Space for Matrix Product
	
	S_matrixProduct = (double **) malloc(sizeof (double*) *matrixSize); 
	for(a = 0; a < matrixSize; a++){
		S_matrixProduct[a] = (double *) malloc(sizeof (double) *matrixSize);
	}
	P_matrixProduct = (double **) malloc(sizeof (double*) *matrixSize); 
	for(a = 0; a < matrixSize; a++){
		P_matrixProduct[a] = (double *) malloc(sizeof (double) *matrixSize);
	}

		//WON"T WORK!
	// malMatrix(matrixOne);
	// malMatrix(matrixTwo);
	// malMatrix(matrixProduct);

	// rNumToMatrix(matrixOne); //only add values to matrix 1 and 2
	// rNumToMatrix(matrixTwo);
}

void malMatrix(double **matrix){
	matrix = (double **) malloc(sizeof (double*) *matrixSize); 
	int a;
	for(a = 0; a < matrixSize; a++){
		matrix[a] = (double *) malloc(sizeof (double) *matrixSize);
	}
}


void rNumToMatrix(double **matrix){
	srand(time(NULL)); //set seeded matrix time!

	int a;
	int b;
	for(a = 0; a < matrixSize; a++){
		for(b = 0; b < matrixSize; b++){
			matrix[a][b] = rand();			
		}
	}
}


/**
 * Reset a given matrix to zeroes
 */
void mmm_reset(double **matrix)
{
	int a;
	int b;
	for (a = 0; a < matrixSize; a++){
		for(b = 0; b < matrixSize; b++){
			matrix[a][b] = 0;
		}
	}
}

/**
 * Free up memory allocated to all matrices
 */
void mmm_freeup()
{
	
	// TODO use the free command to free up the matricies
			//ASK how do I get the adress given no inputs

}

/**
 * Sequential MMM
 */
void mmm_seq()
{
	int a;
	int b;
	for(a = 0; a < matrixSize; a++){
		for(b = 0; b < matrixSize; b++){
			S_matrixProduct[a][b] = (matrixOne[a][b] * matrixTwo[a][b]);
		}
	}
}

/**
 * Parallel MMM
 */
void *mmm_par(void *args)
{
	
	thread_args *params = (thread_args *)args;
	printf("\n args tid: %d first row start: %d last row end: %d\n",params->tid, params->firstRow,params->LastRow);
	// TODO - code to perform parallel MMM
	int a;
	int b;
	for(a = params->firstRow; a < params->LastRow; a++){
		for(b = 0; b < matrixSize; b++){
			P_matrixProduct[a][b] = (matrixOne[a][b] * matrixTwo[a][b]);
		}
	}	
	return NULL;
}




void parallel(){
	pthread_t threads[threadCount];
	thread_args args[threadCount]; //arguments for each of the threads

	int rowsEach = matrixSize/threadCount;//number of rows per thread
	int rowNum = 0; //current row

	
	printf("Number of threads: %d", threadCount);
	printf("Rows each needed: %d", rowsEach);

	
	int i;
	for(i = 0; i < threadCount; i++){
		printf("\nROW NUMBER!!!!!: %d\n",rowNum);

		args[i].tid = i; //set the thread number
		args[i].firstRow = rowNum;
		
		rowNum += rowsEach;
		//Make sure that the last thread takes care of the final rows should the number of rows not be divisable by the number of threads!
		if(i == threadCount-1){
			args[i].LastRow = matrixSize;
			printf("we made it boys");
		}else{
			args[i].LastRow = rowNum;
		}
		
		
		pthread_create(&threads[i], NULL, mmm_par, &args[i]);
		
	}
	
	//reaping!
	int j;
	for(j = 0; j < threadCount; j++){
		pthread_join(threads[j], NULL);
	}	
	printf("\nRows Each! %d",rowsEach);

}

/**
 * Verifies the correctness between the matrices generated by
 * the sequential run and the parallel run.
 *
 * @return the largest error between two corresponding elements
 */
double mmm_verify()
{
	double error;
	
	int a;
	int b;
	for(a = 0; a < matrixSize; a++){
		for(b = 0; b < matrixSize; b++){
			error += fabs(P_matrixProduct[a][b] - S_matrixProduct[a][b]);
		}
	}
	return error;
}


void printMatrix(double **matrix){
	int a;
	int b;
	for(a = 0; a < matrixSize; a++){
		for(b = 0; b < matrixSize; b++){
			printf("%f, ", matrix[a][b]);
		}
		printf("\n");
	}
}

